//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by GitVersion.
// 
// You can modify this code as we will not overwrite it when re-executing GitVersion
// </auto-generated> 
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyFileVersion("3.0.1.0")]
[assembly: AssemblyVersion("3.0.1.0")]
[assembly: AssemblyInformationalVersion("3.0.1+1.Branch.master.Sha.0d6c8b60bd9cfdd71654272f46fd7cff2f275ecd")]