//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by GitVersion.
// 
// You can modify this code as we will not overwrite it when re-executing GitVersion
// </auto-generated> 
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyFileVersion("3.0.1.0")]
[assembly: AssemblyVersion("3.0.1.0")]
[assembly: AssemblyInformationalVersion("3.0.1+Branch.master.Sha.ca2ffe8a7d3e0c2e1d0eb34e2005920a0a3f7336")]