//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by GitVersion.
// 
// You can modify this code as we will not overwrite it when re-executing GitVersion
// </auto-generated> 
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyFileVersion("3.0.2.0")]
[assembly: AssemblyVersion("3.0.2.0")]
[assembly: AssemblyInformationalVersion("3.0.2+2.Branch.master.Sha.70cea0316be51ec48adf0f96cd0728d66f834d78")]